version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "actions:"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory:
      - "/"
      - "/app"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "all:"
    open-pull-requests-limit: 15
