language: android
sudo: required
jdk: oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - ANDROID_API=24
  - EMULATOR_API=21
  - ANDROID_BUILD_TOOLS=24.0.2
  - ADB_INSTALL_TIMEOUT=5
  - secure: cjOA92q6WgrvatDABJI26ytkbKh1wrML2xIfFou2cgGSotW3R1I5taTJqbhNKXhr0ctiomd3N3hYFhUJilv27b8ft2XjsA1hJhrDH1uHiubQ+/xVn7l2DLs9NdgJacmJBqIvMoJsJVHugHLxdzZ0d/0YG3bTAqsy8Zda4cTv6fTSE1Y4g0MDM3Gh/g/LkAX5M/UNmhXwL4fKInWfvXYplkZ4yG5FMXnd5zdXWoYKhTT1LSXWYeII9/YPGBj40qCPiyJsLY0eOhXs/+Vt8S4PeQPu46uQHkZJM2oOGYSa7Kv9aUYDLKD3ybsJsXH/dx0HsgLbxPhDOrRVKf0jtDyOldDWRcJI10z8VuQNpsd1V6NgNcsvESYimAONAwqMyjNNy8z6Ujbr96NOVw0P5Fu/MiZqO0HBD/3zdB4272evyH2TSexzEKrlBqniNc6SVjUCpUpkOe1PckS1HYy73b8FWZ7RmfahQowIK771rr8kA7GeMkfHT8+pMwjoR0NDDBH4Y5IJQtrTDFQGI3i1hzLNvcxbBxI0It0vp6Kz7Ju8Osfif4drIOvl7fA9uMtbfypThSkKd1Qz2NaFKVmd2b4un+8WfYRD/53WoDI8976W6W4SLNJxUqrEGYErCDaW1dir97DRvxvVwyExhKGsus36XR6uiaPT5xYMiQwG1GEgCqA=
  - secure: XpNMdJOkIBQ28Y95bIxJkBhdoWq3RcS01R+qAlSYa7DGfhDbzSk6sa13VBhVqsDFBWewrKmf/r/e99VAkha9Fv2sj8alUUiDPY3MswM6INoOCM75hD+HSb8WYp/iTCdc++DgPS9YwAc4f8/6NHtz9aHZQs+qyAUB/o5VH9X3z520iwA4KGs7WBBkCF3jPHG/IBejhA/lmxKIhbP6svz4K3k2/lFO69JRgTukYGnL0elgUCU/PnyyJxCBFcy9ey0HHDHdvyNFrKphxOS2GpsCEPGaTlAN9mGIeakKFSPNLEEEP2La7z+CLdVHaP94mlmheVHusqiNjvGT/YBgPnBcAIfkxW5caFD9EHv+AljhJ27KCjCSoX+ShU5JX55SmyKnHSTl5cjWh+S4XBfwW/xctegP/yJqop6+nsbFpFnGuk5Tq/8yox/zMyq1qdEIIZ6I7ZfGrUUWheZ0sdsv0aRpWgp8PSIInHjpXOaTAEvJV1wUNwS1obfaUctqMXzIktkumU91jQdW0awNJNQKOH9bxkTc8sjbpx/tvC2MCqjzTdtKAZtjirf+J07M0AG0ocCkPBwXaRNeGkBoWcUJOTYeNQAS05D2VchT9N8DO07iiR/hD5iEVaYE7qamwubJswu8Ky0wlQKsbI+BKF79oMJ99LtA/+l/QQdBxdbU69znrAU=
  - secure: embRkkec6euGVJDni/4Z4Yg+Gjvgi4VqGzE08sk6qpoNbr/Z31Eqbq1jKHvJQAsssXRWWWpnHn3HOzPe2q1USQdgrao1yVNh+l4YlY5TJuV1vcz85y4uB5Z+iXxXJiCsXBLSJiAKq1KxvTGe2xu1ptr6weJDP21Tn+H7LDMJyG1LaWbDPQyMUb0pvjRduS/0F4sWJqxjupzJmvWHwyJB4V/XfnszL1fEBIQhrm5xyM0yYoZUkjTfmM249frhgoQJGE3O1QAS4ticxy+IL2unkDny63IXxzUA5FYZThlTdxaQLWRV0iriDoRx9TS/P93brWgOrrukHc6eBhhYmyC/mhOKyx9DEZEWidrKPrv/Mg26GUAzmq4523jYQRawXQljj9vC/o1ltAcNb/7dWv5uBT4e6j92Y+DMELrw+YPvqDsl9UScnQQRHDBh1eDPLO8kh+YtnE5e2d6tSltK7f+gz2wv0vEjqhlvXzZ+/+k7xJZWAm5fTKm1qTe3ftp9i3/5KIIeVe8PVhLB78ShkbvsP0eMg42Lo1EcYy4Vl5YVxHR23GD903GGMr0BMzwU481TV3BPGZI/W+jcZml5abW06pXm/DPN2cCGL5iFHSpVkgSySb3lxbbBCd5IHPf9ITc+02PUzzEzKq8JG0xrkE1EfC13C2g/rzmjydWf8ADkkhE=
android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - android-$EMULATOR_API_LEVEL
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
  - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
  - build-tools-27.0.3
  - android-26
  - android-25
  - android-24
  - android-23
  - android-22
  - sys-img-armeabi-v7a-android-22
  - extra-android-support
  - extra-android-m2repository
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
- openssl aes-256-cbc -K $encrypted_aaf4a3063d98_key -iv $encrypted_aaf4a3063d98_iv
  -in my_planet.enc -out my_planet -d
- mkdir "$ANDROID_HOME/licenses" || true
- chmod +x gradlew - yes | sdkmanager "platforms;android-28"
- "./gradlew dependencies || true"
install:
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
- echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
- echo y | android update sdk -u -a -t tools
- echo y | android update sdk -u -a -t platform-tools
- echo y | android update sdk -u -a -t build-tools-27.0.1
- echo y | android update sdk -u -a -t android-27
- echo y | android update sdk -u -a -t extra-google-m2repository
- echo y | android update sdk -u -a -t extra-android-m2repository
before_script:
- echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
script:
- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
before_deploy:
- cp $TRAVIS_BUILD_DIR/my_planet $HOME
- cd app/build/outputs/apk/
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/my_planet -storepass $storepass -keypass $keypass app-release-unsigned.apk my_planet
# Verification
- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/24.0.2/zipalign -v 4 app-release-unsigned.apk myPlanet.apk"
deploy:
  provider: releases
  file: myPlanet.apk
  skip_cleanup: true
  on:
    repo: open-learning-exchange/myplanet
    tags: true
    jdk: oraclejdk8
  api_key:
    secure: "EDZAa1awpvW6TrPatpIryndtYneow8usz4bLpjPFGJu3ZxSXWtHHfC49FfRdGSYkEbTzQia95vTrzDk9z45wn1uX4QhhRX17f9HzDrWwNEc4K7SSWpU491K9cgzTW+hJ/S2sa0Ezcfo0Bb1MUFV0bVIaizgRQPKVt5eMHyQCdbPq87qafqWM37kSpI7NcGNqgUU5Ctb8E1GaYyPQlT8RddZrby5Uld1mOlk+0bkmuRWBDHfQRXLMeCileKZDUA2o4rtnoixZijAfaI0DOIyNM75ib3K9jiQFMMmAkFju5KF3PbvLACfn5dXNRDzMHkuNX1bnvwE5DRpKeBHi/NI5DnnNFp+S80e8evVTaht0hdec5nFpgxVYnswg2fUcRyYSKVdA7W8pqgiumvj3iETS6MWccZg0P2prla5+7h61i6StaJkqK8kY5qSwNlLefDvFqxH4ij16PPsaRDvUYteEA5oANZ/tCy9/78qGrvE9dBajwoaKfH3vEQE5aKadNoEWR1urWX4kiwvk0NlxduuHIvRkSFJK+mUO85S7e/bA0U/BxmbyjdOCHSggh3n5t2YmOF1QcHk3prHG1s0ZEOOivL1j0DCTJ6yHGsgd+BRhNWTOK7goABzJHFWyQXtDTfzs3aUA4ItbLTXgRQ9JqI9SvW9udkIW6dUqtVDHkEVXUbc="
after_success:
    - sh scripts/tag.sh