[versions]
kotlin = "2.2.21"
androidGradlePlugin = "8.13.1"
realmGradlePlugin = "10.19.0"
hilt = "2.57.2"
ksp = "2.3.2"
hiltWork = "1.3.0"
media3 = "1.8.0"
retrofit2 = "3.0.0"
markwon = "4.6.2"
annotation = "1.9.1"
appcompat = "1.7.1"
cardview = "1.0.0"
constraintlayout = "2.2.1"
coreKtx = "1.17.0"
preferenceKtx = "1.2.1"
recyclerview = "1.4.0"
securityCrypto = "1.1.0"
slidingpanelayout = "1.2.0"
workRuntime = "2.11.0"
materialDialogs = "0.9.6.0"
materialCalendarView = "1.9.2"
glide = "5.0.5"
photoView = "2.3.0"
fab = "1.6.4"
mpAndroidChart = "v3.1.0"
circularProgressView = "0.1.2"
material = "1.13.0"
gson = "2.13.2"
toggleButtonGroup = "1.2.3"
materialdrawer = "6.1.1"
opencsv = "5.12.0"
okhttp = "5.3.2"
circleimageview = "3.1.0"
pbkdf2 = "1.1.4"
osmdroidAndroid = "6.1.20"
kotlinxSerializationJson = "1.9.0"
kotlinxCoroutinesAndroid = "1.10.2"
androidGifDrawable = "1.2.29"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
realm-gradle-plugin = { module = "io.realm:realm-gradle-plugin", version.ref = "realmGradlePlugin" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
ksp-symbol-processing-gradle-plugin = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version = "2.2.21" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWork" }
hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltWork" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
media3-common = { module = "androidx.media3:media3-common", version.ref = "media3" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
slidingpanelayout = { module = "androidx.slidingpanelayout:slidingpanelayout", version.ref = "slidingpanelayout" }
work-runtime = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }
material-dialogs-commons = { module = "com.afollestad.material-dialogs:commons", version.ref = "materialDialogs" }
material-calendar-view = { module = "com.applandeo:material-calendar-view", version.ref = "materialCalendarView" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
photoView = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoView" }
fab = { module = "com.github.clans:fab", version.ref = "fab" }
mpAndroidChart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpAndroidChart" }
circular-progress-view = { module = "com.github.VaibhavLakhera:Circular-Progress-View", version.ref = "circularProgressView" }
material = { module = "com.google.android.material:material", version.ref = "material" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
toggle-button-group = { module = "com.nex3z:toggle-button-group", version.ref = "toggleButtonGroup" }
materialdrawer = { module = "com.mikepenz:materialdrawer", version.ref = "materialdrawer" }
opencsv = { module = "com.opencsv:opencsv", version.ref = "opencsv" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit2" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
pbkdf2 = { module = "de.rtner:PBKDF2", version.ref = "pbkdf2" }
markwon-editor = { module = "io.noties.markwon:editor", version.ref = "markwon" }
markwon-image = { module = "io.noties.markwon:image", version.ref = "markwon" }
markwon-html = { module = "io.noties.markwon:html", version.ref = "markwon" }
markwon-ext-tables = { module = "io.noties.markwon:ext-tables", version.ref = "markwon" }
osmdroid-android = { module = "org.osmdroid:osmdroid-android", version.ref = "osmdroidAndroid" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
android-gif-drawable = { module = "pl.droidsonroids.gif:android-gif-drawable", version.ref = "androidGifDrawable" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
realm-android = { id = "io.realm.android", version.ref = "realmGradlePlugin" }
