[versions]
android-gradle-plugin = "8.13.1"
kotlin = "2.2.10"
realm = "10.19.0"
hilt = "2.57.2"
hilt-work = "1.3.0"
media3 = "1.8.0"
retrofit = "3.0.0"
markwon = "4.6.2"
annotation = "1.9.1"
appcompat = "1.7.1"
cardview = "1.0.0"
constraintlayout = "2.2.1"
core-ktx = "1.17.0"
localbroadcastmanager = "1.1.0"
preference-ktx = "1.2.1"
recyclerview = "1.4.0"
security-crypto = "1.1.0"
slidingpanelayout = "1.2.0"
work-runtime = "2.11.0"
material-dialogs = "0.9.6.0"
material-calendar-view = "1.9.2"
glide = "5.0.5"
photoview = "2.3.0"
fab = "1.6.4"
mpandroidchart = "v3.1.0"
circular-progress-view = "0.1.2"
material = "1.13.0"
gson = "2.13.2"
toggle-button-group = "1.2.3"
materialdrawer = "6.1.1"
opencsv = "5.12.0"
okhttp = "5.3.0"
circleimageview = "3.1.0"
pbkdf2 = "1.1.4"
osmdroid-android = "6.1.20"
kotlinx-serialization-json = "1.9.0"
kotlinx-coroutines-android = "1.10.2"
android-gif-drawable = "1.2.29"
junit = "4.13.2"
kotlin-bom = "2.2.21"

[libraries]
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "android-gradle-plugin" }
realm-gradle-plugin = { group = "io.realm", name = "realm-gradle-plugin", version.ref = "realm" }
hilt-android-gradle-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hilt-work" }
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt-work" }
androidx-localbroadcastmanager = { group = "androidx.localbroadcastmanager", name = "localbroadcastmanager", version.ref = "localbroadcastmanager" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
androidx-media3-common = { group = "androidx.media3", name = "media3-common", version.ref = "media3" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference-ktx" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "security-crypto" }
androidx-slidingpanelayout = { group = "androidx.slidingpanelayout", name = "slidingpanelayout", version.ref = "slidingpanelayout" }
androidx-work-runtime = { group = "androidx.work", name = "work-runtime", version.ref = "work-runtime" }
material-dialogs-commons = { group = "com.afollestad.material-dialogs", name = "commons", version.ref = "material-dialogs" }
material-calendar-view = { group = "com.applandeo", name = "material-calendar-view", version.ref = "material-calendar-view" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
photoview = { group = "com.github.chrisbanes", name = "PhotoView", version.ref = "photoview" }
fab = { group = "com.github.clans", name = "fab", version.ref = "fab" }
mpandroidchart = { group = "com.github.PhilJay", name = "MPAndroidChart", version.ref = "mpandroidchart" }
circular-progress-view = { group = "com.github.VaibhavLakhera", name = "Circular-Progress-View", version.ref = "circular-progress-view" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
toggle-button-group = { group = "com.nex3z", name = "toggle-button-group", version.ref = "toggle-button-group" }
materialdrawer = { group = "com.mikepenz", name = "materialdrawer", version.ref = "materialdrawer" }
opencsv = { group = "com.opencsv", name = "opencsv", version.ref = "opencsv" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
circleimageview = { group = "de.hdodenhof", name = "circleimageview", version.ref = "circleimageview" }
pbkdf2 = { group = "de.rtner", name = "PBKDF2", version.ref = "pbkdf2" }
markwon-editor = { group = "io.noties.markwon", name = "editor", version.ref = "markwon" }
markwon-image = { group = "io.noties.markwon", name = "image", version.ref = "markwon" }
markwon-html = { group = "io.noties.markwon", name = "html", version.ref = "markwon" }
markwon-ext-tables = { group = "io.noties.markwon", name = "ext-tables", version.ref = "markwon" }
osmdroid-android = { group = "org.osmdroid", name = "osmdroid-android", version.ref = "osmdroid-android" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
android-gif-drawable = { group = "pl.droidsonroids.gif", name = "android-gif-drawable", version.ref = "android-gif-drawable" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin-bom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlin-bom" }


[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
realm-android = { id = "realm-android", version.ref = "realm" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
